### default config ###
spring.profiles.active: development, h2


### development and test config ###
---

spring.profiles: development,test
spring.profiles.include: h2


### Mysql DataSource
---

spring.profiles: mysql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/history?characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      min-idle: 0
      max-idle: 8
      max-active: 8
      pool-prepared-statements: true
      max-wait-millis: 10000

### H2 DataSource
---

spring.profiles: h2

spring.h2.console:
  enabled: true
  path: /h2

spring:
  datasource:
    schema: classpath:sql/schema.sql
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      min-idle: 0
      max-idle: 8
      max-active: 8
      pool-prepared-statements: true
      max-wait-millis: 10000
